site_name: MovingForth
site_author: Eduardo Furlan
copyright: CC BY 4.0 License
repo_name: movingforth
repo_url: http://github.com/efurlanm/movingforth
docs_dir: docs-src
site_dir: docs
# inline html and offline dir navigation
use_directory_urls: false
site_url: ""
## do not use "search"
theme:
    name: material
    font: false
    palette:
# https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
        primary: orange
        accent: orange
    features:
        - header.autohide
extra_css:
    - css/extra.css
plugins:
    - offline
exclude_docs: |
    .ipynb_checkpoints
    .git
